apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-inference.name" . }}
  labels:
    {{- include "fastapi-inference.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fastapi-inference.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fastapi-inference.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: model-store
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: model-store
          persistentVolumeClaim:
            claimName: model-store-pvc
